# -*- coding: utf-8 -*-
"""Part3_Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4BrVwT8HxHhbrxR3dkUc7zr0lsM23Hk
"""

!pip install pyspark

### Part 3

from pyspark.sql import SparkSession

from pyspark import SparkContext

try:
    sc
    print("SparkContext already exists.")
except NameError:
    sc = SparkContext(master="local[1]", appName="CSL7110_Assignment4_PageRank")
    print("New SparkContext created.")

def read_graph_edges(file_path):
    """
    Read graph from file.
    Each line has: source destination
    Duplicate directed edges are removed.
    """
    edges = sc.textFile(file_path) \
        .map(lambda line: line.strip()) \
        .filter(lambda line: line != "") \
        .map(lambda line: tuple(map(int, line.split()))) \
        .distinct()

    return edges

def build_graph(edges_rdd):
    """
    Build adjacency list and node set.

    Returns:
        adjacency_rdd : (src, [dst1, dst2, ...])
        nodes_rdd     : RDD of all node ids
        n             : total number of nodes
    """
    adjacency_rdd = edges_rdd.groupByKey().mapValues(lambda nbrs: list(nbrs)).cache()

    src_nodes = edges_rdd.map(lambda x: x[0])
    dst_nodes = edges_rdd.map(lambda x: x[1])

    nodes_rdd = src_nodes.union(dst_nodes).distinct().cache()
    n = nodes_rdd.count()

    return adjacency_rdd, nodes_rdd, n

def pagerank_spark(file_path, beta=0.8, num_iterations=40):
    """
    Compute PageRank using Spark RDDs.

    Parameters:
        file_path      : graph file path
        beta           : damping factor
        num_iterations : number of iterations

    Returns:
        ranks_rdd : RDD of (node, rank)
        n         : number of nodes
    """
    edges_rdd = read_graph_edges(file_path)
    adjacency_rdd, nodes_rdd, n = build_graph(edges_rdd)

    # Initial rank: 1/n for every node
    initial_rank = 1.0 / n
    ranks_rdd = nodes_rdd.map(lambda node: (node, initial_rank)).cache()

    teleport = (1.0 - beta) / n

    for itr in range(num_iterations):
        # Join adjacency list with current ranks
        # (src, ([neighbors], rank))
        joined = adjacency_rdd.join(ranks_rdd)

        # Distribute rank contribution from each node to its outgoing neighbors
        contributions = joined.flatMap(
            lambda x: [
                (dst, x[1][1] / len(x[1][0]))
                for dst in x[1][0]
            ]
        )

        # Sum incoming contributions for every node
        contrib_sum = contributions.reduceByKey(lambda a, b: a + b)

        # Every node must get rank, even if it gets no incoming contribution
        ranks_rdd = nodes_rdd.map(lambda node: (node, 0.0)) \
            .leftOuterJoin(contrib_sum) \
            .mapValues(lambda x: teleport + beta * (x[1] if x[1] is not None else 0.0)) \
            .cache()

    return ranks_rdd, n

from google.colab import drive
drive.mount('/content/drive')

small_file = "/content/drive/MyDrive/small.txt"
whole_file = "/content/drive/MyDrive/whole.txt"

small_ranks, small_n = pagerank_spark(small_file, beta=0.8, num_iterations=40)

small_top10 = small_ranks.takeOrdered(10, key=lambda x: -x[1])

print("Number of nodes in small graph:", small_n)
print("\nTop 10 nodes in small graph:")
for node, score in small_top10:
    print(node, score)

print("\nTop-most score in small graph:", small_top10[0][1])

whole_ranks, whole_n = pagerank_spark(whole_file, beta=0.8, num_iterations=40)

top5 = whole_ranks.takeOrdered(5, key=lambda x: -x[1])
bottom5 = whole_ranks.takeOrdered(5, key=lambda x: x[1])

print("Number of nodes in whole graph:", whole_n)

print("\nTop 5 nodes with highest PageRank:")
for node, score in top5:
    print(node, score)

print("\nBottom 5 nodes with lowest PageRank:")
for node, score in bottom5:
    print(node, score)

rank_sum = whole_ranks.map(lambda x: x[1]).sum()
print("Sum of PageRank scores =", rank_sum)

